"""Seed Miami across the Beauty, Wellness, and Health networks using the
exact rendered content from the reference site at
david.ai.devintensive.com/miami-knows-*.

Includes:
- City record with hero copy ("ISSUE NO. 01 · MIAMI · MAY 2026" eyebrow,
  hero subhead, search placeholder, stat counts)
- Neighborhoods (with vibe descriptions and the hardcoded "X LISTED"
  counts shown on the reference, NOT derived from the actual editorial
  pick count)
- City-scoped instances of the network's master categories
- Editor's Pick + trending businesses (every business has the exact name,
  category, neighborhood, short description and price shown on the
  reference home page)
- City-level copy blocks for stat counts, search-suggestion chips,
  section titles, footer "Also in..." cities, and the per-network
  "BY {axis}" label and owner CTA stats card.

Run inside the backend container, after seed_networks.py:
    python -m seed.seed_miami
"""

from __future__ import annotations

import json
import os
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

from app.database import ensure_indexes, get_db
from seed._helpers import assert_seed_target_allowed, run, upsert


# Photo URLs scraped from the reference pages (one hero photo per network,
# one image per neighborhood card, one image per business card). The file is
# generated by /tmp/parse-mapping3.py and committed into seed/.
_PHOTOS_PATH = os.path.join(os.path.dirname(__file__), "_photos_by_slug.json")
with open(_PHOTOS_PATH) as _f:
    PHOTOS = json.load(_f)


# Neighborhoods PER NETWORK — each row is (slug, name, vibe, listed_count).
# `listed_count` is the number shown in the "X LISTED" pill on the reference
# neighborhood card. It is NOT derived from the visible editorial picks —
# Sunny Isles Beach for Beauty shows "14 LISTED" even though Beauty Bar Sunny
# is the only editorial pick from that neighborhood.

NEIGHBORHOODS = {
    "beauty": [
        ("wynwood",           "Wynwood",           "Creative & edgy",             2),
        ("brickell",          "Brickell",          "Sleek & corporate",           2),
        ("south-beach",       "South Beach",       "Glamorous & tropical",        1),
        ("coral-gables",      "Coral Gables",      "Refined & classic",           2),
        ("design-district",   "Design District",   "Editorial & luxe",            1),
        ("edgewater",         "Edgewater",         "Emerging & chic",             2),
        ("coconut-grove",     "Coconut Grove",     "Laid-back luxe",              1),
        ("little-havana",     "Little Havana",     "Vibrant & cultural",          2),
        ("sunny-isles-beach", "Sunny Isles Beach", "Tower luxury & multilingual", 14),
        ("aventura",          "Aventura",          "Polished & busy",             1),
        ("bal-harbour",       "Bal Harbour",       "Ultra-luxury",                1),
    ],
    "wellness": [
        ("wynwood",           "Wynwood",           "Creative & experimental", 2),
        ("brickell",          "Brickell",          "Sleek & corporate",       2),
        ("south-beach",       "South Beach",       "Glamorous & tropical",    2),
        ("coral-gables",      "Coral Gables",      "Refined & classic",       1),
        ("design-district",   "Design District",   "Editorial & luxe",        1),
        ("edgewater",         "Edgewater",         "Emerging & chic",         1),
        ("coconut-grove",     "Coconut Grove",     "Laid-back luxe",          1),
        ("sunny-isles-beach", "Sunny Isles Beach", "Tower luxury",            0),
        ("aventura",          "Aventura",          "Polished & busy",         1),
        ("bal-harbour",       "Bal Harbour",       "Ultra-luxury",            0),
        ("little-havana",     "Little Havana",     "Vibrant & cultural",      0),
        ("key-biscayne",      "Key Biscayne",      "Island residential",      1),
    ],
    "health": [
        ("wynwood",           "Wynwood",           "Creative & experimental", 2),
        ("brickell",          "Brickell",          "Sleek & corporate",       2),
        ("south-beach",       "South Beach",       "Glamorous & tropical",    2),
        ("coral-gables",      "Coral Gables",      "Refined & classic",       2),
        ("design-district",   "Design District",   "Editorial & luxe",        1),
        ("edgewater",         "Edgewater",         "Emerging & chic",         1),
        ("coconut-grove",     "Coconut Grove",     "Laid-back luxe",          0),
        ("sunny-isles-beach", "Sunny Isles Beach", "Tower luxury",            0),
        ("aventura",          "Aventura",          "Polished & busy",         1),
        ("bal-harbour",       "Bal Harbour",       "Ultra-luxury",            1),
        ("little-havana",     "Little Havana",     "Vibrant & cultural",      0),
        ("key-biscayne",      "Key Biscayne",      "Island residential",      0),
    ],
}


#: WHY: Each neighborhood page currently shows only a grid of salons with no
#  unique text — Google has nothing to index and no reason to rank the page for
#  searches like "best hair salon in Wynwood" or "nail salons Brickell Miami".
#  These editorial paragraphs give each page its own voice and search signal.
#  They render in the hero section via `neighborhood.hero_description`.
#  Only "beauty" is populated for launch; wellness/health get their own copy
#  when those networks go live.
NEIGHBORHOOD_DESCRIPTIONS: Dict[str, Dict[str, str]] = {
    "beauty": {
        "wynwood": (
            "Where street-art studios and concept salons share the same blocks. "
            "Wynwood's beauty scene is experimental by nature — expect colorists who "
            "treat your hair like a canvas and nail artists whose work ends up on Instagram."
        ),
        "brickell": (
            "Miami's finance district runs on precision, and its salons match. "
            "Brickell is where the city's professionals book sharp cuts and efficient "
            "appointments that hold up in a boardroom and on a rooftop the same night."
        ),
        "south-beach": (
            "Sun-bleached, camera-ready, and international. South Beach salons know how "
            "to make balayage that survives a week of ocean spray — and lashes that "
            "handle a late night without losing their shape."
        ),
        "coral-gables": (
            "Under the banyan trees and behind the limestone facades, Coral Gables holds "
            "some of Miami's most established salons. Quietly expert, long-standing, and "
            "often busier than their subdued storefronts suggest."
        ),
        "design-district": (
            "The same blocks that house Dior and Hermès are home to Miami's most editorial "
            "beauty studios. Expect avant-garde cuts, precision color techniques, and a "
            "level of finish you won't find most other places in the city."
        ),
        "edgewater": (
            "The bay views are new and so are the studios. Edgewater's emerging salon scene "
            "attracts stylists who left established shops to do things on their own terms — "
            "worth getting in with before the rest of Miami figures it out."
        ),
        "coconut-grove": (
            "Shaded by some of Miami's oldest trees, the Grove's salons have a relaxed "
            "confidence that matches the neighborhood. Unhurried appointments, long client "
            "relationships, and real local character."
        ),
        "little-havana": (
            "Beauty culture runs deep in Little Havana. The salons here are part neighborhood "
            "anchor, part creative outlet — and the best ones have been doing it for decades, "
            "long before the rest of Miami started paying attention."
        ),
        "key-biscayne": (
            "Separated from the city by the Rickenbacker Causeway, Key Biscayne moves at "
            "its own unhurried pace. The handful of salons here serve a tight-knit "
            "residential community — expect personalized attention, familiar faces, "
            "and a clientele that has been coming back for years."
        ),
        "sunny-isles-beach": (
            "With one of the most multilingual client bases in Miami, Sunny Isles salons are "
            "fluent in global beauty standards — Russian, Portuguese, Spanish, and the "
            "universal language of a great blowout with ocean light coming through the window."
        ),
        "aventura": (
            "Polished, efficient, and close to the mall. Aventura's salon corridor serves a "
            "busy, well-heeled clientele who know exactly what they want and don't like to "
            "wait — the booking flow here tends to be tight."
        ),
        "bal-harbour": (
            "A short walk from the most exclusive boutiques in Florida, Bal Harbour's salons "
            "set the standard for luxury treatments in Miami. Availability is limited — "
            "these are the appointments people plan around."
        ),
    },
}


# Handcrafted-showcase business arrays were removed in favor of real,
# verifiable Miami businesses loaded from _real_businesses.json. The empty
# lists below are kept so the merge helper still finds expected names.

BEAUTY_BUSINESSES:   List[Dict[str, Any]] = []
WELLNESS_BUSINESSES: List[Dict[str, Any]] = []
HEALTH_BUSINESSES:   List[Dict[str, Any]] = []


# Per-network city-level configuration, all taken from the reference pages.
#
# Hero title structure: the editorial italic phrase is bracketed in
# `headline_html` with <em>...</em> so the template can render it directly
# (rather than guessing which words to italicize).
NETWORK_CITY_CONFIG = {
    "beauty": {
        "tagline": "Miami's best-kept beauty addresses.",
        "headline_html": "Miami's<br><em class=\"italic font-normal text-amber-100/95\">best-kept</em><br>beauty addresses.",
        "hero_eyebrow": "ISSUE NO. 01 · MIAMI · MAY 2026",
        "hero_subhead": "An index of the stylists, colorists, esthetes, and barbers locals actually book — neighborhood by neighborhood.",
        "search_placeholder": "Balayage in Wynwood. Gel manicure in Brickell. Quiet barbershop near Coral Gables.",
        "stat_count_listings": "29",
        "stat_label_listings": "SALONS INDEXED",
        "stat_count_neighborhoods": "11",
        "stat_count_editor_picks": "5",
        "stat_label_owners": "FOR SALON OWNERS",
        "search_chips": ["balayage", "gel manicure", "lash extensions", "hydrafacial", "fade"],
        "header_nav": [
            ("hair",      "Hair"),
            ("nails",     "Nails"),
            ("spa",       "Spa"),
            ("lash-brow", "Lashes"),
            ("med-spa",   "Med Spa"),
            ("barber",    "Barber"),
        ],
        "header_owners_cta": "For Salon Owners",
        "browse_axis_label": "BY SERVICE",
        "map_culture_word": "beauty",
        "owners_eyebrow": "FOR SALON OWNERS",
        "owners_headline": "Own a salon in Miami?",
        "owners_italic": "Your listing's already here.",
        "owners_body": "We've pre-built a profile for every salon in Miami. Claim yours in 3 minutes, tell us your story by voice, and get found by people searching tonight.",
        "owners_cta": "Claim your salon · Free",
        "owners_card_business_slug": "rossano-ferretti-hair-spa-miami",
        "owners_card_stats": {
            "views": "3,128",
            "calls": "112",
            "bookings": "+31",
            "bookings_label": "New bookings (Voice)",
        },
        "owners_card_action": "Post your golden-hour blowout reel to Instagram — <span class=\"text-rose-600 underline\">draft ready</span>",
        "listing_word_plural":   "Salons",
        "listing_word_singular": "salon",
        "spotlight_neighborhood_slug": "wynwood",
        "spotlight_eyebrow": "NEIGHBORHOOD SPOTLIGHT",
        "spotlight_lead_a": "What's",
        "spotlight_lead_b": "happening in",
        "spotlight_description": "Street-art murals meet experimental beauty studios.",
        "spotlight_business_slugs": ["wynwood-hair-co", "nue-studio-wynwood", "the-spot-barbershop-wynwood"],
        "footer_blurb": "The curated directory of Miami's best salons, spas, and beauty professionals. Discovered by locals, loved by visitors.",
        "footer_also_in": "Also in Boca Raton",
        "footer_also_in_url": "https://boca.knowsbeauty.com",
        "footer_publication_label": "A Knows Beauty publication.",
        "footer_owners_label": "SALONS",
        "footer_owners_items": ["List your salon", "Pricing"],
        "footer_legal": "© 2026 Miami Knows Beauty · A local-first directory for beauty professionals.",
        "footer_made_in": "Made in Miami · Powered by Expertly",
        "seo_title": "Miami Knows Beauty",
        "trending_business_slugs": [
            "rossano-ferretti-hair-spa-miami",
            "elia-spa-ritz-carlton-south-beach",
            "vanity-projects-miami-design-district",
            "igk-salon-south-beach",
            "the-spa-at-the-setai",
        ],
        "two_column_neighborhoods": [
            {"slug": "south-beach", "business_slugs": ["igk-salon-south-beach", "elia-spa-ritz-carlton-south-beach", "the-spa-at-the-setai"]},
            {"slug": "brickell",    "business_slugs": ["blow-dry-bar-brickell", "the-broward-brow-studio-brickell"]},
        ],
    },
    "wellness": {
        "tagline": "Where Miami recovers, resets, and breathes.",
        "headline_html": "Where Miami<br><em class=\"italic font-normal text-amber-100/95\">recovers,</em><br>resets, and<br>breathes.",
        "hero_eyebrow": "ISSUE NO. 01 · MIAMI · MAY 2026",
        "hero_subhead": "An index of the spas, saunas, recovery rooms, yoga studios, and IV lounges Miami locals actually book — between training blocks, after long flights, and before the week gets loud.",
        "search_placeholder": "Infrared sauna in Wynwood. Sunrise yoga in Edgewater. IV drip in Brickell.",
        "stat_count_listings": "418",
        "stat_label_listings": "STUDIOS INDEXED",
        "stat_count_neighborhoods": "12",
        "stat_count_editor_picks": "5",
        "stat_label_owners": "FOR OWNERS",
        "search_chips": ["infrared sauna", "cold plunge", "sunrise yoga", "IV drip", "reformer pilates"],
        "header_nav": [
            ("spa",             "Spa"),
            ("recovery",        "Recovery"),
            ("iv-hydration",    "IV & Hydration"),
            ("yoga-meditation", "Yoga & Meditation"),
            ("holistic",        "Holistic"),
            ("nutrition",       "Nutrition"),
        ],
        "header_owners_cta": "For Owners",
        "browse_axis_label": "BY WELLNESS",
        "map_culture_word": "wellness",
        "owners_eyebrow": "FOR WELLNESS OWNERS",
        "owners_headline": "Run a wellness practice in Miami?",
        "owners_italic": "Your listing's already here.",
        "owners_body": "We pre-built a profile for every studio, spa, and recovery room in Miami. Claim yours in three minutes — and get found by people searching tonight.",
        "owners_cta": "Claim your studio · Free",
        "owners_card_business_slug": "restore-hyper-wellness-miami",
        "owners_card_stats": {
            "views": "2,847",
            "calls": "94",
            "bookings": "+22",
            "bookings_label": "New bookings",
        },
        "owners_card_action": "Post your contrast-therapy reel — <span class=\"text-emerald-600 underline\">draft ready</span>",
        "listing_word_plural":   "Studios",
        "listing_word_singular": "studio",
        "spotlight_neighborhood_slug": "wynwood",
        "spotlight_eyebrow": "NEIGHBORHOOD SPOTLIGHT",
        "spotlight_lead_a": "Where Miami's",
        "spotlight_lead_b": "recovery culture lives —",
        "spotlight_description": "A few converted warehouses and brick-walled studios are quietly leading the recovery scene. Here is who is doing it well.",
        "spotlight_business_slugs": ["the-sweat-shop-wynwood", "pause-studio-miami", "the-sacred-space-miami"],
        "footer_blurb": "The curated guide to Miami spas, recovery, yoga, and wellness — discovered by locals, kept simple.",
        "footer_also_in": "Coming soon to Austin · Orlando · Dallas",
        "footer_publication_label": "A Knows Wellness publication.",
        "footer_owners_label": "WELLNESS",
        "footer_owners_items": ["Claim your listing", "Pricing", "Miami Knows Beauty →"],
        "footer_legal": "© 2026 Miami Knows Wellness · A local-first directory.",
        "footer_made_in": "Made in Miami · Powered by Expertly",
        "seo_title": "Miami Knows Wellness",
        "trending_business_slugs": [
            "ahimsa-yoga-music-center-miami",
            "green-monkey-yoga-miami",
            "restore-hyper-wellness-miami",
            "spa-ritz-carlton-south-beach",
            "lapis-spa-fontainebleau-miami-beach",
            "the-sweat-shop-wynwood",
            "spa-st-regis-bal-harbour",
            "pause-studio-miami",
        ],
        "two_column_neighborhoods": [
            {"slug": "south-beach", "business_slugs": ["spa-ritz-carlton-south-beach", "miami-life-center-miami-beach"]},
            {"slug": "wynwood",    "business_slugs": ["the-sweat-shop-wynwood", "pause-studio-miami", "the-sacred-space-miami"]},
        ],
    },
    "health": {
        "tagline": "Miami's most-trusted doctors, dentists, and clinics.",
        "headline_html": "Miami's<br><em class=\"italic font-normal text-amber-100/95\">most-trusted</em><br>doctors, dentists, and clinics.",
        "hero_eyebrow": "ISSUE NO. 01 · MIAMI · MAY 2026",
        "hero_subhead": "A neutral, locally curated guide to the longevity clinics, dental practices, mental health groups, fertility specialists, and concierge primary-care doctors Miami families and professionals trust.",
        "search_placeholder": "Concierge doctor in Brickell. Invisalign in Coral Gables. Couples therapist in Wynwood.",
        "stat_count_listings": "627",
        "stat_label_listings": "PRACTICES INDEXED",
        "stat_count_neighborhoods": "12",
        "stat_count_editor_picks": "4",
        "stat_label_owners": "FOR PRACTICES",
        "search_chips": ["concierge doctor", "invisalign", "pelvic floor PT", "hormone therapy", "couples therapy"],
        "header_nav": [
            ("aesthetics",     "Aesthetics"),
            ("metabolic",      "Metabolic"),
            ("longevity",      "Longevity"),
            ("dental",         "Dental"),
            ("mental-health",  "Mental Health"),
            ("fertility",      "Fertility"),
        ],
        "header_owners_cta": "For Owners",
        "browse_axis_label": "BY HEALTH",
        "map_culture_word": "health",
        "owners_eyebrow": "FOR PRACTICES",
        "owners_headline": "Run a practice in Miami?",
        "owners_italic": "Your listing's already here.",
        "owners_body": "We pre-built a profile for every clinic and practice in Miami-Dade. Claim yours, correct details, and add the things that matter — your training, your approach, your office.",
        "owners_cta": "Claim your practice · Free",
        "owners_card_business_slug": "cleveland-clinic-florida-orthopaedic-sports-medicine-center-aventura",
        "owners_card_stats": {
            "views": "2,847",
            "calls": "94",
            "bookings": "+22",
            "bookings_label": "New bookings",
        },
        "owners_card_action": "Post your patient-trust update — <span class=\"text-sky-700 underline\">draft ready</span>",
        "listing_word_plural":   "Clinics",
        "listing_word_singular": "clinic",
        "spotlight_neighborhood_slug": "brickell",
        "spotlight_eyebrow": "NEIGHBORHOOD SPOTLIGHT",
        "spotlight_lead_a": "Where Miami professionals",
        "spotlight_lead_b": "see their doctors —",
        "spotlight_description": "The tower-medicine corridor — concierge primary care, longevity clinics, and specialists who keep the same patients for decades.",
        "spotlight_business_slugs": ["platinum-physical-therapy-brickell", "concierge-medicine-of-south-florida-brickell"],
        "footer_blurb": "A curated guide to Miami's clinics and providers — provider-focused, not outcome-promising.",
        "footer_also_in": "Coming soon to Austin · Orlando · Dallas",
        "footer_publication_label": "A Knows Health publication.",
        "footer_owners_label": "HEALTH",
        "footer_owners_items": ["Claim your listing", "Pricing", "Miami Knows Beauty →"],
        "footer_legal": "© 2026 Miami Knows Health · A local-first directory.",
        "footer_made_in": "Made in Miami · Powered by Expertly",
        "seo_title": "Miami Knows Health",
        "trending_business_slugs": [
            "cleveland-clinic-florida-orthopaedic-sports-medicine-center-aventura",
            "sabal-palm-house-mental-health-treatment-center",
            "garcia-facial-plastic-surgery-coral-gables",
            "platinum-physical-therapy-brickell",
            "the-movement-lab-wynwood",
            "sidelinger-md",
            "concierge-medicine-of-south-florida-brickell",
            "the-biostation-miami",
        ],
        "two_column_neighborhoods": [
            {"slug": "coral-gables", "business_slugs": ["garcia-facial-plastic-surgery-coral-gables", "sabal-palm-house-mental-health-treatment-center"]},
            {"slug": "brickell",     "business_slugs": ["platinum-physical-therapy-brickell", "concierge-medicine-of-south-florida-brickell"]},
        ],
    },
}


# Fallback Unsplash photo URLs by category. Used for the bulk-loaded "real"
# businesses below — those came from an LLM lookup that returns names, addresses
# and editorial blurbs but no photo URLs. Each category gets a generic but
# topical photo so cards don't render with empty hero space.
_CATEGORY_FALLBACK_PHOTOS: Dict[str, str] = {
    # beauty
    "hair":            "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=1600&q=80&auto=format&fit=crop",
    "nails":           "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=1600&q=80&auto=format&fit=crop",
    "spa":             "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1600&q=80&auto=format&fit=crop",
    "lash-brow":       "https://images.unsplash.com/photo-1583241800698-e8ab01830a07?w=1600&q=80&auto=format&fit=crop",
    "med-spa":         "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=1600&q=80&auto=format&fit=crop",
    "barber":          "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=1600&q=80&auto=format&fit=crop",
    "makeup":          "https://images.unsplash.com/photo-1487070183336-b863922373d4?w=1600&q=80&auto=format&fit=crop",
    "waxing":          "https://images.unsplash.com/photo-1556228852-80b6e5eeff06?w=1600&q=80&auto=format&fit=crop",
    # wellness
    "recovery":        "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1600&q=80&auto=format&fit=crop",
    "iv-hydration":    "https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=1600&q=80&auto=format&fit=crop",
    "yoga-meditation": "https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=1600&q=80&auto=format&fit=crop",
    "holistic":        "https://images.unsplash.com/photo-1591343395082-e120087004b4?w=1600&q=80&auto=format&fit=crop",
    "nutrition":       "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=1600&q=80&auto=format&fit=crop",
    "sleep-stress":    "https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=1600&q=80&auto=format&fit=crop",
    "retreats":        "https://images.unsplash.com/photo-1540206395-68808572332f?w=1600&q=80&auto=format&fit=crop",
    # health
    "aesthetics":      "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=1600&q=80&auto=format&fit=crop",
    "metabolic":       "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=1600&q=80&auto=format&fit=crop",
    "longevity":       "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=1600&q=80&auto=format&fit=crop",
    "dental":          "https://images.unsplash.com/photo-1606811971618-4486d14f3f99?w=1600&q=80&auto=format&fit=crop",
    "mental-health":   "https://images.unsplash.com/photo-1573497019418-b400bb3ab074?w=1600&q=80&auto=format&fit=crop",
    "fertility":       "https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=1600&q=80&auto=format&fit=crop",
    "pt-recovery":     "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1600&q=80&auto=format&fit=crop",
    "primary-care":    "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=1600&q=80&auto=format&fit=crop",
}


def _load_real_businesses() -> Dict[str, List[Dict[str, Any]]]:
    """Load the LLM-generated 'real' businesses and reshape into the same
    structure the handcrafted showcase entries use, so they can be merged.
    """
    import json as _json
    path = Path(__file__).parent / "_real_businesses.json"
    if not path.exists():
        return {"beauty": [], "wellness": [], "health": []}
    raw = _json.loads(path.read_text())
    out: Dict[str, List[Dict[str, Any]]] = {}
    for net, items in raw.items():
        rows: List[Dict[str, Any]] = []
        for it in items:
            rows.append({
                "slug": it["slug"],
                "name": it["name"],
                "category_slugs":     [it["category_slug"]],
                "neighborhood_slugs": [it["neighborhood_slug"]],
                "price_cues":         it.get("price_cues"),
                "editors_pick":       bool(it.get("editors_pick")),
                "premium":            bool(it.get("premium")),
                # WHY: mock "Founding Partner" flag for the design-partner
                # outreach demo. Stays false unless the source JSON explicitly
                # opts a business in.
                "is_founding_partner": bool(it.get("is_founding_partner")),
                "short_description":  it.get("short_description"),
                "phone":              it.get("phone"),
                "website":            it.get("website"),
                "instagram":          it.get("instagram"),
                "address_full":       it.get("address"),
                # No specific photo from the LLM — fall back to a category photo
                "photo_url":          _CATEGORY_FALLBACK_PHOTOS.get(it["category_slug"]),
                # WHY: seed-time services let us pre-populate curated menus for
                # outreach-target businesses before any owner claims the listing.
                # On re-seed the existing DB services are preserved (see upsert
                # logic below), so this only sets services for brand-new inserts.
                "services":           it.get("services", []),
            })
        out[net] = rows
    return out


def _merged_businesses() -> Dict[str, List[Dict[str, Any]]]:
    """Combine the handcrafted showcase entries with the LLM-generated real
    businesses. Handcrafted entries win on slug collision (their rich blurbs
    and curated home-page placements are referenced elsewhere in the seed).
    """
    real = _load_real_businesses()
    merged: Dict[str, List[Dict[str, Any]]] = {}
    for net, showcase in (
        ("beauty",   BEAUTY_BUSINESSES),
        ("wellness", WELLNESS_BUSINESSES),
        ("health",   HEALTH_BUSINESSES),
    ):
        by_slug: Dict[str, Dict[str, Any]] = {}
        for b in real.get(net, []):
            by_slug[b["slug"]] = b
        for b in showcase:
            by_slug[b["slug"]] = b  # showcase wins on slug collision
        merged[net] = list(by_slug.values())
    return merged


BUSINESSES_PER_NETWORK = _merged_businesses()


async def _set_copy(scope_type: str, scope_ref: Dict[str, str], key: str, value: str) -> None:
    """Upsert a single copy block."""
    db = get_db()
    now = datetime.now(timezone.utc)
    existing = await db.copy_blocks.find_one({
        "scope_type": scope_type, "scope_ref": scope_ref, "key": key, "locale": "en-US",
    })
    if existing:
        await db.copy_blocks.update_one(
            {"_id": existing["_id"]},
            {"$set": {"value": value, "updated_at": now}},
        )
    else:
        await db.copy_blocks.insert_one({
            "_id": str(uuid.uuid4()),
            "scope_type": scope_type,
            "scope_ref": scope_ref,
            "key": key,
            "value": value,
            "locale": "en-US",
            "active_from": None,
            "active_until": None,
            "created_at": now,
            "updated_at": now,
        })


async def seed_network(network_slug: str) -> None:
    db = get_db()
    network = await db.networks.find_one({"slug": network_slug})
    if not network:
        print(f"Network {network_slug} not found — run seed_networks.py first.")
        return

    cfg = NETWORK_CITY_CONFIG[network_slug]
    businesses = BUSINESSES_PER_NETWORK[network_slug]
    now = datetime.now(timezone.utc)

    # City
    city_doc = {
        "_id": str(uuid.uuid4()),
        "network_id": network["_id"],
        "slug": "miami",
        "name": "Miami",
        "state": "FL",
        "country": "US",
        "timezone": "America/New_York",
        "tagline": cfg["tagline"],
        "hero_description": cfg["hero_subhead"],
        "seo_title": cfg["seo_title"],
        "meta_description": cfg["hero_subhead"],
        "editorial_headlines": [{"headline": cfg["tagline"], "is_default": True}],
        "status": "live",
        "created_at": now,
        "updated_at": now,
    }
    city = await upsert("cities", {"network_id": network["_id"], "slug": "miami"}, city_doc)

    # Wipe and re-add neighborhoods so a re-seed cleanly matches the reference
    # (the upsert would otherwise leave behind older neighborhoods like
    # "Mid-Beach", "Downtown" etc. that aren't in the reference list).
    await db.neighborhoods.delete_many({
        "city_id": city["_id"],
        "slug": {"$nin": [n[0] for n in NEIGHBORHOODS[network_slug]]},
    })
    nb_photos = PHOTOS.get(network_slug, {}).get("neighborhoods", {})
    for i, (slug, name, vibe, listed_count) in enumerate(NEIGHBORHOODS[network_slug]):
        nb_doc = {
            "_id": str(uuid.uuid4()),
            "city_id": city["_id"],
            "slug": slug,
            "name": name,
            "description": vibe,
            #: WHY: hero_description is the editorial paragraph that appears below
            #  the italic vibe quote in the neighborhood hero section. Without it the
            #  page has no unique text for Google to index, so it can't rank for
            #  "best [service] in [neighborhood]" searches. Populated from
            #  NEIGHBORHOOD_DESCRIPTIONS above; None for networks/neighborhoods not
            #  yet written.
            "hero_description": NEIGHBORHOOD_DESCRIPTIONS.get(network_slug, {}).get(slug),
            "listed_count": listed_count,
            "photo_url": nb_photos.get(slug),
            "order": i,
            "status": "live",
            "created_at": now,
            "updated_at": now,
        }
        await upsert("neighborhoods", {"city_id": city["_id"], "slug": slug}, nb_doc)

    # Wipe and re-add categories the same way.
    master_slugs = [g["slug"] for g in (network.get("category_map") or [])]
    await db.categories.delete_many({
        "city_id": city["_id"],
        "slug": {"$nin": master_slugs},
    })
    for order, group in enumerate(network.get("category_map") or []):
        cat_doc = {
            "_id": str(uuid.uuid4()),
            "network_id": network["_id"],
            "city_id": city["_id"],
            "slug": group["slug"],
            "parent_slug": None,
            "name": group["name"],
            "description": group.get("description"),
            "meta_description": group.get("meta_description"),
            "examples": group.get("examples", []),
            "order": order,
            "status": "live",
            "created_at": now,
            "updated_at": now,
        }
        await upsert("categories", {"city_id": city["_id"], "slug": group["slug"]}, cat_doc)

    # Wipe stale EDITORIAL businesses from earlier seeds so the editorial list
    # on the home page matches the reference exactly (no leftover "Stillwater
    # Spa" or "Gables Cosmetic Dentistry" from prior runs).
    # WHY: only delete editorial records — Fresha imports, manual additions,
    # and claimed businesses have data_source != 'editorial' (or claim_status
    # != 'unclaimed') and must survive across seed runs so they aren't wiped
    # when the seed refreshes the handcrafted list.
    canonical_biz_slugs = [b["slug"] for b in businesses]
    await db.businesses.delete_many({
        "city_id": city["_id"],
        "slug": {"$nin": canonical_biz_slugs},
        "data_source": "editorial",
        "claim_status": "unclaimed",
    })

    # Businesses
    biz_photos = PHOTOS.get(network_slug, {}).get("businesses", {})
    for biz in businesses:
        # Per-business curated photo wins when we have one; otherwise keep the
        # category-based fallback URL that was set when the business was loaded.
        # Without this guard, AI-sourced businesses (which have no per-slug
        # photo entry) would end up with no image at all on the live site.
        per_biz_photo = biz_photos.get(biz["slug"])
        if per_biz_photo:
            biz["photo_url"] = per_biz_photo
        featured = (
            {"enabled": True, "tier": "premium"} if biz.get("premium") else
            {"enabled": False, "tier": "free"}
        )
        photos = [{"url": biz["photo_url"]}] if biz.get("photo_url") else []
        # Use the LLM-supplied street address if we have one; otherwise fall back
        # to the bare city stub. The frontend formats it as "{street}, {city}".
        address: Dict[str, Any] = {"city": "Miami", "state": "FL", "country": "US"}
        if biz.get("address_full"):
            address["street"] = biz["address_full"]
        # Socials block for the business detail sidebar.
        socials: Dict[str, Any] = {}
        if biz.get("instagram"):
            socials["instagram"] = biz["instagram"]
        biz_doc = {
            "_id": str(uuid.uuid4()),
            "network_id": network["_id"],
            "city_id": city["_id"],
            "slug": biz["slug"],
            "name": biz["name"],
            "category_slugs": biz["category_slugs"],
            "neighborhood_slugs": biz.get("neighborhood_slugs", []),
            "short_description": biz.get("short_description"),
            "known_for": biz.get("short_description"),
            "price_cues": biz.get("price_cues"),
            "featured": featured,
            "editors_pick": biz.get("editors_pick", False),
            # WHY: persists the mock founding-partner flag so the home and
            # detail templates can render the badge from a single field.
            "is_founding_partner": biz.get("is_founding_partner", False),
            # WHY: editorial picks are our quality judgment about the listing,
            # NOT confirmation that the owner has gone through the claim flow.
            # Seeding as 'verified' hides the Claim CTA for every editors'-pick
            # salon — exactly the owners we most want to onboard. All editorial
            # listings start unclaimed; claim_status advances to 'claimed' or
            # 'verified' only when a real owner completes the claim flow.
            "claim_status": "unclaimed",
            "schema_org_type": biz.get("schema_org_type", "LocalBusiness"),
            "data_source": "editorial",
            "quality_score": 90 if biz.get("editors_pick") else 60,
            "index_status": "indexed",
            "index_override": "auto",
            "status": "live",
            "address": address,
            "phone": biz.get("phone"),
            "website": biz.get("website"),
            "instagram": biz.get("instagram"),
            "socials": socials,
            "hours": [],
            "services": [],
            "photos": photos,
            "created_at": now,
            "updated_at": now,
        }
        # WHY: the generic upsert() does a full replace_one, which wipes services,
        # claim data, and Stripe billing fields on every deploy. Owners who've set
        # up a service menu or completed the claim flow would lose their work.
        # Instead, carry those fields forward from the existing document while
        # still refreshing editorial metadata (name, description, photos, etc.).
        existing_biz = await db.businesses.find_one(
            {"city_id": city["_id"], "slug": biz["slug"]}
        )
        if existing_biz:
            for _preserve in (
                "claim_status",
                "claimed_email",
                "claimed_by_user_id",
                "claimed_at",
                "verified_at",
                "stripe_customer_id",
                "stripe_subscription_id",
                # WHY: is_founding_partner from the DB always wins over the seed JSON
                # value — an admin may have toggled the flag after first insert, and
                # a re-seed should never override that decision.
                "is_founding_partner",
                "hours",
            ):
                if _preserve in existing_biz:
                    biz_doc[_preserve] = existing_biz[_preserve]
            # WHY: services are a special case — only preserve the DB copy when it is
            # non-empty (meaning an owner or admin actually set them). An empty list
            # means "not yet populated" OR "was wiped by the deploy bug". In either
            # case, fall back to the curated seed services so outreach targets keep
            # their menus through every re-deploy.
            existing_services = existing_biz.get("services") or []
            if existing_services:
                biz_doc["services"] = existing_services
            elif biz.get("services"):
                biz_doc["services"] = biz["services"]
            biz_doc["_id"] = existing_biz["_id"]
            biz_doc["created_at"] = existing_biz.get("created_at", biz_doc["created_at"])
            await db.businesses.replace_one({"_id": existing_biz["_id"]}, biz_doc)
        else:
            # New business: seed the curated service menu from the JSON if provided.
            if biz.get("services"):
                biz_doc["services"] = biz["services"]
            await db.businesses.insert_one(biz_doc)

    # City-level copy blocks for the structural strings that appear on the
    # home page (the same ones an editor would later tweak through the API).
    scope = {"city_id": city["_id"]}
    pairs = [
        ("home.hero.eyebrow",        cfg["hero_eyebrow"]),
        ("home.hero.subhead",        cfg["hero_subhead"]),
        ("home.hero.headline",       cfg["tagline"]),
        ("home.hero.headline_html",  cfg["headline_html"]),
        ("home.hero.search_placeholder", cfg["search_placeholder"]),
        ("home.stat.listings.count", cfg["stat_count_listings"]),
        ("home.stat.listings.label", cfg["stat_label_listings"]),
        ("home.stat.neighborhoods.count", cfg["stat_count_neighborhoods"]),
        ("home.stat.editor_picks.count",  cfg["stat_count_editor_picks"]),
        ("home.stat.owners.label",   cfg["stat_label_owners"]),
        ("home.browse.axis_label",   cfg["browse_axis_label"]),
        ("home.map.culture_word",    cfg["map_culture_word"]),
        ("home.editor_picks.eyebrow","★ EDITOR'S PICKS"),
        ("home.editor_picks.title",  "The ones we'd send a friend to"),
        ("home.trending.eyebrow",    "THIS WEEK"),
        ("home.trending.title",      "Trending in Miami"),
        ("home.spotlight.eyebrow",   cfg["spotlight_eyebrow"]),
        ("home.spotlight.lead_a",    cfg["spotlight_lead_a"]),
        ("home.spotlight.lead_b",    cfg["spotlight_lead_b"]),
        ("home.spotlight.description", cfg["spotlight_description"]),
        ("home.owners.eyebrow",      cfg["owners_eyebrow"]),
        ("home.owners.headline",     cfg["owners_headline"]),
        ("home.owners.italic",       cfg["owners_italic"]),
        ("home.owners.body",         cfg["owners_body"]),
        ("home.owners.cta",          cfg["owners_cta"]),
        ("home.owners.card_action",  cfg["owners_card_action"]),
        ("home.owners.card_stats.views",         cfg["owners_card_stats"]["views"]),
        ("home.owners.card_stats.calls",         cfg["owners_card_stats"]["calls"]),
        ("home.owners.card_stats.bookings",      cfg["owners_card_stats"]["bookings"]),
        ("home.owners.card_stats.bookings_label", cfg["owners_card_stats"]["bookings_label"]),
        ("header.owners_cta",        cfg["header_owners_cta"]),
        ("footer.about.body",        cfg["footer_blurb"]),
        ("footer.also_in",           cfg["footer_also_in"]),
        ("footer.also_in_url",       cfg.get("footer_also_in_url", "")),
        ("footer.publication_label", cfg["footer_publication_label"]),
        ("footer.owners.label",      cfg["footer_owners_label"]),
        ("footer.owners.items",      " | ".join(cfg["footer_owners_items"])),
        ("footer.legal",             cfg["footer_legal"]),
        ("footer.made_in",           cfg["footer_made_in"]),
    ]
    for key, value in pairs:
        await _set_copy("city", scope, key, value)

    # Configuration that's structural, not free text — keep on the city
    # doc itself so the route can read it without a copy-block lookup.
    await get_db().cities.update_one(
        {"_id": city["_id"]},
        {"$set": {
            "spotlight_neighborhood_slug": cfg["spotlight_neighborhood_slug"],
            "spotlight_business_slugs":    cfg["spotlight_business_slugs"],
            "owners_card_business_slug":   cfg["owners_card_business_slug"],
            "trending_business_slugs":     cfg["trending_business_slugs"],
            "two_column_neighborhoods":    cfg["two_column_neighborhoods"],
            "search_chips":                cfg["search_chips"],
            "header_nav":                  [{"slug": s, "label": l} for s, l in cfg["header_nav"]],
            # Per-network word for what a single listing is called. Beauty
            # calls them "salons", Wellness "studios", Health "clinics". The
            # category page title uses the plural ("Hair Salons in Miami");
            # the neighborhood count chip uses the singular+s ("2 salons listed").
            "listing_word_plural":         cfg.get("listing_word_plural", "Listings"),
            "listing_word_singular":       cfg.get("listing_word_singular", "listing"),
            "hero_photo_url":              PHOTOS.get(network_slug, {}).get("hero"),
            "updated_at": now,
        }},
    )

    print(f"  Seeded {network_slug} / miami: "
          f"{len(NEIGHBORHOODS[network_slug])} neighborhoods, "
          f"{len(network.get('category_map') or [])} categories, "
          f"{len(businesses)} businesses.")


async def main() -> None:
    # WHY: this seed DELETES stale neighborhoods/categories/businesses as part
    # of re-seeding (see the delete_many calls in seed_network). Refuse to run
    # against a production database unless explicitly confirmed, before any DB
    # access, so a wrong-database run aborts with nothing wiped. See
    # seed._helpers.assert_seed_target_allowed.
    assert_seed_target_allowed()
    await ensure_indexes()
    for slug in ("beauty", "wellness", "health"):
        print(f"== Seeding Miami for {slug} ==")
        await seed_network(slug)


if __name__ == "__main__":
    run(main())
